# Generated by Django 2.2.7 on 2019-12-06 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20191204_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 15, 20, 38, 77149, tzinfo=utc)),
        ),
    ]
