# Generated by Django 2.2.7 on 2019-12-06 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20191206_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 18, 49, 23, 904397, tzinfo=utc)),
        ),
    ]
