# Generated by Django 2.2.7 on 2019-12-09 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0017_auto_20191209_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 13, 48, 14, 655235, tzinfo=utc)),
        ),
    ]
