# Generated by Django 2.2.7 on 2019-12-09 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_auto_20191209_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 17, 3, 14, 529991, tzinfo=utc)),
        ),
    ]
