# Generated by Django 2.2.7 on 2019-12-07 23:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20191207_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='job_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posts.JobPost'),
        ),
        migrations.AlterField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 23, 57, 57, 15811, tzinfo=utc)),
        ),
    ]
