# Generated by Django 2.2.7 on 2019-12-07 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20191207_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posts.JobPost'),
        ),
        migrations.AlterField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 23, 59, 7, 728006, tzinfo=utc)),
        ),
    ]
