# Generated by Django 2.2.7 on 2019-12-12 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20191209_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 3, 29, 7, 70000, tzinfo=utc)),
        ),
    ]
