# Generated by Django 2.2.7 on 2019-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191202_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/default_profile_picure.png', upload_to='users/'),
        ),
    ]
