# Generated by Django 2.2.7 on 2019-12-06 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('associated_with', models.CharField(max_length=150)),
                ('description', tinymce.models.HTMLField()),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2019, 12, 6, 16, 42, 0, 834311, tzinfo=utc))),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 12, 6, 16, 42, 0, 834344, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
