# Generated by Django 2.2.7 on 2019-12-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default='', max_length=63)),
                ('headline', models.CharField(blank=True, max_length=75, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
