# Generated by Django 2.2.7 on 2019-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_users', '0002_remove_candidateinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
