# Generated by Django 2.2.7 on 2019-11-29 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0004_auto_20191129_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 21, 53, 43, 301951, tzinfo=utc)),
        ),
    ]
