# Generated by Django 2.2.7 on 2019-11-29 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0006_auto_20191129_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 22, 7, 29, 815662, tzinfo=utc)),
        ),
    ]
