# Generated by Django 2.2.7 on 2019-11-29 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0007_auto_20191129_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 22, 8, 21, 62672, tzinfo=utc)),
        ),
    ]
