# Generated by Django 2.2.7 on 2019-11-29 22:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0008_auto_20191129_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 22, 18, 17, 178328, tzinfo=utc)),
        ),
    ]
