# Generated by Django 2.2.7 on 2019-12-03 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0025_auto_20191202_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 19, 8, 19, 441202, tzinfo=utc)),
        ),
    ]
