# Generated by Django 2.2.7 on 2019-12-07 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0036_auto_20191207_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 22, 24, 59, 498471, tzinfo=utc)),
        ),
    ]
