# Generated by Django 2.2.7 on 2019-12-09 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0044_auto_20191207_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 5, 43, 23, 895092, tzinfo=utc)),
        ),
    ]
