# Generated by Django 2.2.7 on 2019-12-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='location',
        ),
    ]
