# Generated by Django 2.2.7 on 2019-12-06 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_auto_20191206_2040'),
        ('candidate_users', '0003_candidateinfo_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 20, 39, 59, 895225, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 20, 39, 59, 895276, tzinfo=utc)),
        ),
    ]
