# Generated by Django 2.2.7 on 2019-12-07 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_users', '0006_auto_20191207_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='city',
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 22, 24, 59, 505831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 22, 24, 59, 505867, tzinfo=utc)),
        ),
    ]
