# Generated by Django 2.2.7 on 2019-12-09 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_users', '0016_auto_20191209_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 16, 55, 31, 546956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 16, 55, 31, 546982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
