# Generated by Django 2.2.7 on 2019-12-02 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0015_auto_20191202_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 14, 52, 22, 1954, tzinfo=utc)),
        ),
    ]
