# Generated by Django 2.2.7 on 2019-12-02 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0019_auto_20191202_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 15, 0, 23, 554348, tzinfo=utc)),
        ),
    ]
