# Generated by Django 2.2.7 on 2019-12-02 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0023_auto_20191202_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 18, 30, 33, 839187, tzinfo=utc)),
        ),
    ]
