# Generated by Django 2.2.7 on 2019-12-04 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0026_auto_20191203_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 13, 47, 28, 375880, tzinfo=utc)),
        ),
    ]
