# Generated by Django 2.2.7 on 2019-12-04 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0028_auto_20191204_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 17, 52, 55, 335069, tzinfo=utc)),
        ),
    ]
