# Generated by Django 2.2.7 on 2019-12-06 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0032_auto_20191206_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 15, 41, 21, 891145, tzinfo=utc)),
        ),
    ]
