# Generated by Django 2.2.7 on 2019-12-07 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0034_auto_20191206_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 21, 24, 49, 645105, tzinfo=utc)),
        ),
    ]
