# Generated by Django 2.2.7 on 2019-12-07 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0041_auto_20191207_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 23, 50, 41, 20667, tzinfo=utc)),
        ),
    ]
