# Generated by Django 2.2.7 on 2019-12-12 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0048_auto_20191212_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 5, 7, 19, 638742, tzinfo=utc)),
        ),
    ]
