# Generated by Django 2.2.7 on 2019-12-07 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_auto_20191207_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 23, 48, 10, 776590, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 23, 48, 10, 776616, tzinfo=utc)),
        ),
    ]
