# Generated by Django 2.2.7 on 2019-12-04 20:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_auto_20191204_2025'),
        ('company_users', '0031_auto_20191204_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('remote', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=155)),
                ('employment_type', models.CharField(max_length=75)),
                ('description', tinymce.models.HTMLField()),
                ('industry', models.CharField(max_length=155)),
                ('active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2019, 12, 4, 20, 25, 11, 161605, tzinfo=utc))),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 12, 4, 20, 25, 11, 161639, tzinfo=utc))),
                ('company_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_users.Company')),
                ('skills', models.ManyToManyField(to='skills.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
