# Generated by Django 2.2.7 on 2019-12-07 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_liked', models.BooleanField(blank=True, null=True)),
                ('candidate_liked', models.BooleanField(blank=True, null=True)),
                ('company_liked_timestamp', models.DateTimeField(blank=True, null=True)),
                ('candidate_liked_timestamp', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 12, 7, 21, 43, 18, 45632, tzinfo=utc))),
                ('candidate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('company_user_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
