# Generated by Django 2.2.7 on 2019-12-07 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 22, 24, 59, 515335, tzinfo=utc)),
        ),
    ]
