# Generated by Django 2.2.7 on 2019-12-07 23:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0013_auto_20191207_2353'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='job_post',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posts.JobPost'),
        ),
        migrations.AlterField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 23, 53, 38, 661657, tzinfo=utc)),
        ),
    ]
