# Generated by Django 2.2.7 on 2019-12-09 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0015_auto_20191209_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 17, 3, 14, 539191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 17, 3, 14, 539227, tzinfo=utc)),
        ),
    ]
