# Generated by Django 2.2.7 on 2019-12-06 19:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('employment_type', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('description', tinymce.models.HTMLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2019, 12, 6, 19, 4, 0, 882792, tzinfo=utc))),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 12, 6, 19, 4, 0, 882834, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
