# Generated by Django 2.2.7 on 2019-12-06 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_auto_20191206_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 20, 39, 59, 893852, tzinfo=utc)),
        ),
    ]
