# Generated by Django 2.2.7 on 2019-12-07 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_auto_20191207_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 21, 43, 18, 21367, tzinfo=utc)),
        ),
    ]
