# Generated by Django 2.2.7 on 2019-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191129_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.IntegerField(default=False),
        ),
    ]
