# Generated by Django 2.2.7 on 2019-12-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0014_auto_20191202_1450'),
        ('users', '0006_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company_users.Company'),
            preserve_default=False,
        ),
    ]
